Repository vipulsinha97/Dating_project, pull requests merged in 2025-02, with the labels that each got.

#203 Amir_Hasan: Responsive Feedback changes fix
  assets/css/homepage-style.css
  resources/views/includes/header.blade.php
Labels: enhancement

#204 Amir_Hasan: Responsive Feedback changes fix
  assets/css/homepage-style.css
  resources/views/includes/header.blade.php
Labels: enhancement

#205 Amir_Hasan: Registration form Fields added
  resources/views/includes/header.blade.php
  resources/views/signup/signup-details.blade.php
Labels: enhancement

#206 Amir_Hasan: Registration form Fields added
  resources/views/includes/header.blade.php
  resources/views/signup/signup-details.blade.php
Labels: enhancement

#207 Amir_Hasan: social links to 1st step
  resources/views/signup/signup-details.blade.php
Labels: enhancement

#209 Vipul_Sinha: New Changes
  app/Http/Controllers/WebsiteController.php
  app/Http/Controllers/loginController.php
  app/Http/Controllers/signupController.php
  resources/views/includes/header.blade.php
Labels: bug

#210 Vipul_Sinha: New Changes
  app/Http/Controllers/WebsiteController.php
  app/Http/Controllers/loginController.php
  app/Http/Controllers/signupController.php
  resources/views/includes/header.blade.php
Labels: bug

#211 Vipul_Sinha:Bug fixes
  app/Http/Controllers/WebsiteController.php
  app/Http/Controllers/signupController.php
  app/Http/Controllers/socialController.php
  app/Http/Requests/StoreRegistrationRequest.php
  app/Services/RegistrationServices.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/migrations/2024_09_21_135602_update_user_table2.php
  resources/views/dashboard/admin/allUsers.blade.php
  resources/views/dashboard/admin/pendingUsers.blade.php
  resources/views/home.blade.php
  resources/views/signup/signup-details.blade.php
Labels: bug

#214 Vipul_Sinha:Issue fixed
  app/Http/Controllers/WebsiteController.php
  app/Http/Controllers/loginController.php
  resources/views/home.blade.php
  resources/views/includes/header.blade.php
  resources/views/login/login.blade.php
  resources/views/signup/signup-details.blade.php
  resources/views/signup/signup.blade.php
Labels: bug

#215 Amir hasan: approve btn
  resources/views/dashboard/admin/pendingUsers.blade.php
Labels: bug

#216 Amir_Hasan: Pending req
  resources/views/dashboard/admin/pendingUsers.blade.php
Labels: bug

#217 Vipul_Sinha:New forget password functionaltiy
  app/Http/Controllers/PasswordResetController.php
  app/Http/Controllers/socialController.php
  assets/js/homepage-script.js
  database/migrations/2025_02_11_233425_create_password_resets_table.php
  resources/views/dashboard/admin/event.blade.php
  resources/views/emails/password_reset.blade.php
  resources/views/event.blade.php
  resources/views/includes/bottom.blade.php
  resources/views/resetPassword.blade.php
  routes/web.php
Labels: bug, enhancement

#218 Vipul sinha:Forget Password functionality
  app/Http/Controllers/PasswordResetController.php
  app/Http/Controllers/socialController.php
  assets/js/homepage-script.js
  database/migrations/2025_02_11_233425_create_password_resets_table.php
  resources/views/dashboard/admin/event.blade.php
  resources/views/emails/password_reset.blade.php
  resources/views/event.blade.php
  resources/views/includes/bottom.blade.php
  resources/views/resetPassword.blade.php
  routes/web.php
Labels: bug, enhancement
